### ISSUE TITLE
Greate Idea

### ISSUE THREAD

**Issue by codmpm** [node-enocean/node-red-contrib-enocean#1]
THIS is a great idea! 

Do you plan to support the USB300, or any other direct hardware, or use a gateway like the existing node-red-contrib-enoceanip?

Keep the naming of the node in mind: 
> Node modules should use node-red-contrib- as a prefix to their name to make it clear they are not maintained by the Node-RED project. Alternatively, any name that doesn’t use node-red as a prefix can be used.

(from https://nodered.org/docs/creating-nodes/packaging)

**Comment by codmpm** [comment]
Ok. I've just saw, that the likely underlying node-enocean supports direct hardware access.

Superb!!

**Comment by Holger-Will** [comment]
ok, i will rename the repository...

**Comment by Holger-Will** [comment]
closing as there now is a basic implementation...
