### ISSUE TITLE
Teach in Jung Button

### ISSUE THREAD

**Issue by Rolf-M** [node-enocean/node-red-contrib-enocean#10]
Hello all,
I try to teach in a "Jung" Button Module, but even with a seperate teach in node I don't get any result.
The raw data recived when pressing the lower left button is "55000707017af610002fb67a3001ffffffff5200fc"
I don't know if this is related to node-red-contrib-enocean or rather related to the underlaying node-js part node-enocean.
Could anybody help?
Here is the link to the manufacturers website of the button
https://www.jung.de/de/online-katalog/62517751/
Regards, Rolf

**Comment by Holger-Will** [comment]
please try the new implementation https://github.com/enocean-js/enocean-js/tree/master/packages/node-red-contrib-enocean
