### ISSUE TITLE
A5-04-03 eep

### ISSUE THREAD

**Issue by lynkev10** [node-enocean/node-red-contrib-enocean#11]
I am using the Enocean Listener and it is working great. Is there a easy way to get the temperature and humidity out of the object? Or is it in the works to create a node for the A5-04 profiles?

![object](https://user-images.githubusercontent.com/35104366/37775388-34f7d0c8-2db9-11e8-8cd7-22b747e6f6d8.JPG)

**Comment by mley** [comment]
I'm having the same issue with the Enocean STM 33x. 
```
timestamp: 1538202604776
rawByte: "55000e07014030fad46a73fddfec0a050c67570001ffffffff3100ee"
packetType: 1
senderId: "050c6757"
choice: "30"
subTelNum: 1
destinationId: "ffffffff"
rssi: 49
securityLevel: 0
```

I am using the bare PCB version obtained from Farnell.
I assumed, that it may get decoded after the device was teached-in, but even when following the steps mentioned in https://github.com/node-enocean/node-red-contrib-enocean/issues/6#issuecomment-328794046 only gives the data of the telegram above. Yes, I used the teach-in button of the STM 33x (shorting WAKE1 to GND for < 10s ).


Mmmh. Continuing to read the documentation of the module (https://www.enocean.com/de/enocean-module/details/stm-330/user-manual-pdf/) in 3.9.2 it states:

> In case of a wake-up via WAKE1 pin (LRN input) the module transmits a teach-in telegram.
>  If the manufacturer code is not set, the module transmits a normal telegram according
> to 3.9.1 with the difference that DI_3=0.
>  If a Manufacturer ID is set, this teach-in telegram contains special information as de-
> scribed below. By default EnOcean Manufacturer ID is set. Customer can configure their own. 

I fear, I have to set a manufacturer ID in the STM module. Maybe I should have paid the extra money to get a vendored version. ¯\_(ツ)_/¯

**Comment by Holger-Will** [comment]
if you are still working on this, please try the new version and ask questions over at the monorepo: https://github.com/enocean-js/enocean-js/tree/master/packages/node-red-contrib-enocean
