### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by cflurin** [node-enocean/node-red-contrib-enocean#5]
Hi,

I've installed `node-red-contrib-enocean` as described in the documentation on a Raspberry Pi 3.
As soon as I configure the config-node (Serialport: /dev/ttyUSB0) I get an error `SyntaxError: missing ) after argument list`.

```sh
Welcome to Node-RED
===================
29 Aug 14:39:38 - [info] Node-RED version: v0.17.5
29 Aug 14:39:38 - [info] Node.js  version: v6.11.2
29 Aug 14:39:38 - [info] Linux 4.9.41-v7+ arm LE
29 Aug 14:39:41 - [info] Loading palette nodes
...
29 Aug 14:53:00 - [error] [enocean-config-node:93400904.cc4848] SyntaxError: missing ) after argument list
29 Aug 14:53:00 - [error] [enocean-listener:f803abda.300b48] TypeError: Cannot read property 'enocean' of null
```

**Comment by nabbl** [comment]
Hi.

You need one of the newer nodeJs versions (>=7.0).

This is because of the node-enocean library using asynchronous functions.

Be careful when updating nodejs though. You will need to clean your
node_modules folder of node-red and then npm install...

**Comment by cflurin** [comment]
Thanks for your quick reply. The node-red developers recommend to use node.js v6.x and to avoid node.js  v7.x. Is there a solution with node.js v6.x.?

**Comment by Holger-Will** [comment]
yes, you can pass a commandline parameter when starting node-red.

    node --harmony-async-await red.js

**Comment by cflurin** [comment]
@Holger-Will: it seems v6.x doesn't support this option:

```sh
node --harmony-async-await red.js
node: bad option: --harmony-async-await
```

**Comment by cflurin** [comment]
... I think the best solution is to motivate the node-red developers to move to node.js V7

**Comment by nabbl** [comment]
I am currently using Node-Red with the newest 8.x NodeJS version.

It works without any apparent flaws.

I added a hint on the Readme.md to only use this with node version > 7.0

This is a serious limitation I know but the nodeJS upgrade at node-red should come sooner rather than later... And I don't see any issues using a newer version regardless.

Issue closed.

**Comment by cflurin** [comment]
Ok thanks, I'll wait until node.js/node-red officially recommends a higher version than v6.
It'd be helpful if you would add a note (node.js v7 required) in your documentation.
