### ISSUE TITLE
Teach in new sensors doesn't work

### ISSUE THREAD

**Issue by mikkomultanen** [node-enocean/node-red-contrib-enocean#6]
Steps:
1. inject string to enocean listener
2. press Eltako button
3. Nothing happens

I get the injected string and button events to debug node but no sensor is added to enocean listener device list.

Node-RED version: v0.17.5
Node.js  version: v8.4.0
Linux 4.9.41+ arm LE

**Comment by nabbl** [comment]
I am going to test that tonight. Sounds odd because it worked a few days ago on my machine.

**Comment by mikkomultanen** [comment]
Maybe the node-enocean doesn't recognize the button. Can I somehow get eep from the button events to check if node-enocean supports it?

**Comment by Holger-Will** [comment]
Buttons are mostly encoded wit f6-xx-xx telegrams. Theses RPS telegrams do not support tech-in procedure with publication of its own EEP. Node-enocean currently assumes f6-02-03 for all RPS (f6) telegrams. If your button sends any other telegram automatic teach in does not work, or more precisely the wrong type will be thoght in...
It should in any way show up though...

**Comment by Holger-Will** [comment]
can you post the raw telegram string? it seems from the description here https://www.eltako.com/fileadmin/downloads/de/Gesamtkatalog/Eltako_Gesamtkatalog_KapT_low_res.pdf
that Eltaco is sending the right data bytes of f6-02-03 but with the wrong ORG (0x05) which is not supported... that's a possible explanation why no teach in is happening... adding support should be trivial though...

**Comment by mikkomultanen** [comment]
This is the button 1 pressed event: 55000707017af630fefd8a5a3001ffffffff3a00a6

**Comment by Holger-Will** [comment]
thanks. that looks like a regular f6-02-03 telegram and should work normally...

**Comment by nabbl** [comment]
I tested it on my system again. I saw that there is a problem when you use the Enocean Listener Node as  a Teach-In Node simultaneously. It then filters the teach-in telegram...

I would suggest to have a dedicated Teach-In Node. (Just add the Listener Node from the palette and set the Configuration). Hookup an Inject Node and send some String. Press the Enocean Rocker Button in between 30 seconds and it should work. You should be able to see the new button (maybe after page refresh) in the original listener Node.... DONT use your teach-in node to validate this however.

[Some Example how I set it up](https://imgur.com/a/huZIl)

**Comment by Holger-Will** [comment]
"It then filters the teach-in telegram..." it shouldn't really do that... let me see if i can debug the problem a bit more. I might find time to do it this weekend.
